"'Screen Configurations' As screen":

    ctnViewConfig As groupContainer.manualLayoutContainer:
        Height: =685
        Width: =1366
        Y: =83
        ZIndex: =1

        btnGerenciarAcessos As button:
            BorderThickness: =3
            Color: =RGBA(24, 56, 132, 1)
            Fill: =RGBA(255, 255, 255, 1)
            Font: =Font.'Open Sans Condensed'
            Height: =178
            OnSelect: |+
                =Navigate('Screen Manage Access',ScreenTransition.CoverRight);
                
            RadiusBottomLeft: =2
            RadiusBottomRight: =2
            RadiusTopLeft: =2
            RadiusTopRight: =2
            Size: =20
            Text: ="Gerenciamento de Acessos"
            Width: =186
            X: =153
            Y: =57
            ZIndex: =1

    ctnViewConfigHeader As groupContainer.manualLayoutContainer:
        Height: =83
        Width: =1366
        ZIndex: =2

        rectConfigHeader As rectangle:
            Fill: =RGBA(24, 56, 132, 1)
            Height: =2
            Width: =1232
            X: =108
            Y: =72
            ZIndex: =1

        lblConfigClientes As label:
            Color: =RGBA(24, 56, 132, 1)
            Fill: =RGBA(24, 56, 132, 0)
            Font: =Font.Verdana
            FontWeight: =FontWeight.Semibold
            Height: =52
            PaddingLeft: =0
            Size: =25
            Text: ="CONFIGURAÇÕES"
            Width: =1232
            X: =108
            Y: =20
            ZIndex: =2

        icoConfigVoltar As icon.ArrowLeft:
            Color: =RGBA(24, 56, 132, 1)
            Icon: =Icon.ArrowLeft
            OnSelect: =Navigate('Screen Page Home',ScreenTransition.UnCoverRight)
            X: =20
            Y: =19
            ZIndex: =3

